name: Make-Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  DOCKER_IMAGE_NAME: crownair/ticket

jobs:
  build:

    runs-on: Ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    # - name: test
    #   run: make test
    - name: build
      run: make BASE=docker.io NAME=$DOCKER_IMAGE_NAME VERSION=$(date +'%Y%m%d%H%M%S')${GITHUB_SHA:6} docker

    - name: Publish to Registry
      run: docker push $DOCKER_IMAGE_NAME --creds $CRED
      env:
        CRED: ${{ secrets.DOCKER_HUB_USERNAME }}:${{ secrets.DOCKER_HUB_PASSWORD }}
