name: Make-Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Rust MUSL Builder
      uses: NSCoder/rust-musl-action@v1.0.0
    - name: test
      run: make test
    - name: build
      run: make release
