name: Make-Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare musl-tool
      run: sudo apt update && sudo apt install musl-tools pkg-config -y
    - name: test
      run: make test
    - name: build
      run: make release
